- hosts: ci-servers
  sudo: True
  tasks:
  - include: utilities/main.yml
  - roles:
    - geerlingguy.java
    - lino.tomcat7
    - geerlingguy.git
     
  - name: installing jenkins container
    docker:
      name: jenkins
      image: jenkins:2.7.4
      state: started
      ports:
       - 8080:8080
      expose:
       - 6379
      volumes:
       - jenkins_home:/var/jenkins_home
       
  - name: installing regsitry container
    docker:
     name: registry
     image: registry:2
     state: started
     ports:
      - 5000:5000
     links:
      - jenkins

  - name: installing artifactory container
    docker:
     name: artifactory
     image: jfrog-docker-registry.bintray.io/jfrog/artifactory-pro:4.1.0 
     state: started
     ports:
      - 8081:8081
     env:
       ARTIFACTORY_HOME=/var/opt/jfrog/artifactory 
     volumes:
      - /data:$ARTIFACTORY_HOME/data
      - /logs:$ARTIFACTORY_HOME/logs
      - /backup:$ARTIFACTORY_HOME/backup
      - /etc:$ARTIFACTORY_HOME/etc 
     links:
      - jenkins
