
- hosts: dev-servers
  sudo: True
  tasks:
  - include: common/main.yml

  - name: running mysql docker container
    docker:
     name: mysql
     image: centurylink/mysql
     state: started
     expose:
      - 3306
     env:
         MYSQL_DATABASE=moodle
         MYSQL_USER=moodle
         MYSQL_PASSWORD=moodle

  - name: building moodle image
    docker_image:
     name: moodle
     tag: moodle
     path: dev-env/moodle-docker
     state: build
  - name: run moodle container
    docker:
     name: moodle:moodle
     state: started
     ports:
      - 8080:80
     volumes:
      - dev-env/moodle-docker/foreground.sh:/etc/apache2/foreground.sh
     links:
      - mysql
  - name: build node.js app image 
    docker_image:
      name: node_app
      tag: node
      path: dev-env
      state: build
  - name: run node.js app container 
    docker:
     name:
     ports:
      - 3000:3000
      - 35729:35729
     volumes:
      - app/config:/usr/src/app/config
      - app/modules:/usr/src/app/modules
      - app/public:/usr/src/app/public
     env:
       MOODLE_URL=http://docker-host-ofdevvm:8080
       MOODLE_SERVICE=appname_mobile_app
       ANGULAR_EXPIRATION_HOURS_AUTH=24
